-ignorewarnings
-keep,includedescriptorclasses public class com.google.firebase.analytics.FirebaseAnalytics { *; }
-keep,includedescriptorclasses public class com.google.firebase.example.LoggingUtils { * ; }