-ignorewarnings
-keep,includedescriptorclasses public class com.google.firebase.example.LoggingUtils { * ; }
-keep,includedescriptorclasses public class com.google.firebase.installations.FirebaseInstallations { *; }
-keep,includedescriptorclasses public class com.google.firebase.installations.InstallationTokenResult { *; }