-ignorewarnings
-keep,includedescriptorclasses public class com.google.android.gms.messaging.cpp.DebugLogging { *; }
-keep,includedescriptorclasses public class com.google.android.gms.messaging.cpp.ListenerService { *; }
-keep,includedescriptorclasses public class com.google.android.gms.messaging.cpp.RegistrationIntentService { *; }
-keep,includedescriptorclasses public class com.google.firebase.example.LoggingUtils { * ; }
-keep,includedescriptorclasses public class com.google.firebase.example.SampleNativeActivity { * ; }
-keep,includedescriptorclasses public class com.google.firebase.messaging.FirebaseMessaging { *; }
-keep,includedescriptorclasses public class com.google.firebase.messaging.cpp.RegistrationIntentService { *; }
-keep,includedescriptorclasses public class java.lang.IllegalArgumentException { *; }