# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sweetspace (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sweetspace (iOS)
  pod 'Firebase/Core'
  pod 'Google-Mobile-Ads-SDK'

end

target 'Sweetspace (Mac)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sweetspace (Mac)

end

target 'Sweetspace(Sim)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sweetspace(Sim)
  pod 'Firebase/Core'
  pod 'Google-Mobile-Ads-SDK'

end
